spring:
  main:
    allow-bean-definition-overriding: true
  security:
  application:
    name: AUTH-SERVICE

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/myvault}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
app:
  upload:
    base-path: ./uploads
    avatar:
      path: ./uploads/avatars
      max-size: 2097152  # 2MB
      allowed-types: [ jpg, jpeg, png, gif ]
    document:
      path: ./uploads/documents
      max-size: 10485760  # 10MB
      allowed-types: [ pdf, doc, docx, jpg, png ]

server:
  port: 8081

security:
  jwt:
    token:
      secret-key: secret-value

openapi:
  dev-url: "http://localhost:8081"
  prod-url: "https://authservice.ru"
  email: "example@gmail.com"
  name: "Author"
  url: "https://authservice.ru"