spring:
  main:
    allow-bean-definition-overriding: true
  security:
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${AUTH_DATABASE_URL:jdbc:postgresql://db:5432/consultra}
    username: ${AUTH_DATABASE_USERNAME:postgres}
    password: ${AUTH_DATABASE_PASSWORD:maoirt}
    schema: public
    liquibase:
      default-schema: public
    logging:
      level:
        liquibase: DEBUG
  profiles:
    active: ${AUTH_SPRING_PROFILES_ACTIVE:prod}

notification:
  service:
    url: ${AUTH_NOTIFICATION_SERVICE_URL:http://notification-service:8081}

app:
  cors:
    allowed-origins: ${AUTH_CORS_ALLOWED_ORIGINS:http://frontend:80,http://localhost:3000,https://your-frontend-domain.onrender.com}
  frontend:
    url: ${FRONTEND_URL:http://frontend:80}
  upload:
    base-path: ${UPLOAD_BASE_PATH:./uploads}
    avatar:
      path: ${UPLOAD_AVATAR_PATH:./uploads/avatars}
      max-size: 2097152
      allowed-types: [ jpg, jpeg, png, gif ]
    document:
      path: ${UPLOAD_DOCUMENT_PATH:./uploads/documents}
      max-size: 10485760
      allowed-types: [ pdf, doc, docx, jpg, png ]

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${AUTH_DATABASE_URL:jdbc:postgresql://db:5432/consultra}
    username: ${AUTH_DATABASE_USERNAME:postgres}
    password: ${AUTH_DATABASE_PASSWORD:maoirt}
    schema: public
    liquibase:
      default-schema: public
    logging:
      level:
        liquibase: DEBUG

notification:
  service:
    url: ${AUTH_NOTIFICATION_SERVICE_URL:http://notification-service:8081}

server:
  port: ${PORT:8080}

security:
  jwt:
    token:
      secret-key: ${AUTH_JWT_SECRET_KEY:secret-value}

openapi:
  dev-url: ${OPENAPI_DEV_URL:http://localhost:8081}
  prod-url: ${OPENAPI_PROD_URL:https://your-auth-service-domain.onrender.com}
  email: ${OPENAPI_EMAIL:example@gmail.com}
  name: ${OPENAPI_NAME:Author}
  url: ${OPENAPI_URL:https://your-auth-service-domain.onrender.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    disk:
      enabled: true

logging:
  level:
    root: INFO
    com.example.auth_service: DEBUG
    com.example.auth_service.controller: DEBUG
    com.example.auth_service.service: DEBUG
    com.example.auth_service.repository: DEBUG
    com.example.auth_service.security: DEBUG
    liquibase: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log
    max-size: 10MB
    max-history: 30