spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:maoirtx77@gmail.com}
    password: ${EMAIL_PASSWORD:kzyu lpcs ywqt khzk}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

email:
  subject: Email Verification
  message: Click the link to verify your email


server:
  port: 8081