spring:
  application:
    name: notification-service

  mail:
    host: ${NOTIFICATION_EMAIL_HOST:smtp.gmail.com}
    port: ${NOTIFICATION_EMAIL_PORT:587}
    username: ${NOTIFICATION_EMAIL_USERNAME:maoirtx77@gmail.com}
    password: ${NOTIFICATION_EMAIL_PASSWORD:kzyu lpcs ywqt khzk}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

email:
  subject: ${NOTIFICATION_EMAIL_SUBJECT:Email Verification}
  message: ${NOTIFICATION_EMAIL_MESSAGE:Click the link to verify your email}

server:
  port: ${PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    disk:
      enabled: true