version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "${AUTH_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
      notification-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${AUTH_SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_DATASOURCE_URL=${AUTH_DATABASE_URL:-jdbc:postgresql://db:5432/consultra}
      - SPRING_DATASOURCE_USERNAME=${AUTH_DATABASE_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_DATABASE_PASSWORD:-maoirt}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - NOTIFICATION_SERVICE_URL=${AUTH_NOTIFICATION_SERVICE_URL:-http://notification-service:8081}
      - CORS_ALLOWED_ORIGINS=${AUTH_CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://frontend:80}
      - JWT_SECRET_KEY=${AUTH_JWT_SECRET_KEY:-secret-value}
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -v http://localhost:8080/actuator/health || echo 'Health check failed'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network
  notification-service:
    build: ./notification-service
    ports:
      - "${NOTIFICATION_PORT:-8081}:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=${NOTIFICATION_SPRING_PROFILES_ACTIVE:-prod}
      - EMAIL_USERNAME=${NOTIFICATION_EMAIL_USERNAME:-maoirtx77@gmail.com}
      - EMAIL_PASSWORD=${NOTIFICATION_EMAIL_PASSWORD:-kzyu lpcs ywqt khzk}
      - EMAIL_HOST=${NOTIFICATION_EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${NOTIFICATION_EMAIL_PORT:-587}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - auth-service
    environment:
      - REACT_APP_API_URL=${FRONTEND_REACT_APP_API_URL:-http://localhost:8080}
      - REACT_APP_WS_URL=${FRONTEND_REACT_APP_WS_URL:-ws://localhost:8080}
    networks:
      - app-network
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_POSTGRES_DB:-consultra}
      - POSTGRES_USER=${DB_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD:-maoirt}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d consultra"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
