version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  notification-service:
    build: ./notification-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service 