[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTimeout = 1800

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPort = 8080

# Database Variables (Railway PostgreSQL)
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
PGDATABASE = "${{Postgres.PGDATABASE}}"
PGUSER = "${{Postgres.PGUSER}}"
PGPASSWORD = "${{Postgres.PGPASSWORD}}"
POSTGRES_DB = "${{Postgres.POSTGRES_DB}}"

# Auth Service Variables
AUTH_SPRING_PROFILES_ACTIVE = "prod"
AUTH_DATABASE_URL = "${{Postgres.DATABASE_URL}}"
AUTH_DATABASE_USERNAME = "${{Postgres.PGUSER}}"
AUTH_DATABASE_PASSWORD = "${{Postgres.PGPASSWORD}}"
AUTH_NOTIFICATION_SERVICE_URL = "http://localhost:8081"
AUTH_CORS_ALLOWED_ORIGINS = "http://localhost:80,http://frontend:80"
AUTH_JWT_SECRET_KEY = "consultra-secret-key-2024"
AUTH_PORT = "8080"

# Notification Service Variables
NOTIFICATION_SPRING_PROFILES_ACTIVE = "prod"
NOTIFICATION_EMAIL_USERNAME = "maoirtx77@gmail.com"
NOTIFICATION_EMAIL_PASSWORD = "kzyu lpcs ywqt khzk"
NOTIFICATION_EMAIL_HOST = "smtp.gmail.com"
NOTIFICATION_EMAIL_PORT = "587"
NOTIFICATION_EMAIL_SUBJECT = "Email Verification"
NOTIFICATION_EMAIL_MESSAGE = "Click the link to verify your email"
NOTIFICATION_PORT = "8081"

# Frontend Variables
FRONTEND_REACT_APP_API_URL = "http://localhost:8080"
FRONTEND_REACT_APP_WS_URL = "ws://localhost:8080"
FRONTEND_PORT = "80" 