[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPort = 8080

[env]
# Auth Service Variables
AUTH_SPRING_PROFILES_ACTIVE = "prod"
AUTH_DATABASE_URL = "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
AUTH_DATABASE_USERNAME = "${PGUSER}"
AUTH_DATABASE_PASSWORD = "${PGPASSWORD}"
AUTH_NOTIFICATION_SERVICE_URL = "http://localhost:8081"
AUTH_CORS_ALLOWED_ORIGINS = "http://localhost:80,http://frontend:80"
AUTH_JWT_SECRET_KEY = "your-secret-key-here"
AUTH_PORT = "8080"

# Notification Service Variables
NOTIFICATION_SPRING_PROFILES_ACTIVE = "prod"
NOTIFICATION_EMAIL_USERNAME = "maoirtx77@gmail.com"
NOTIFICATION_EMAIL_PASSWORD = "kzyu lpcs ywqt khzk"
NOTIFICATION_EMAIL_HOST = "smtp.gmail.com"
NOTIFICATION_EMAIL_PORT = "587"
NOTIFICATION_EMAIL_SUBJECT = "Email Verification"
NOTIFICATION_EMAIL_MESSAGE = "Click the link to verify your email"
NOTIFICATION_PORT = "8081"

# Frontend Variables
REACT_APP_API_URL = "http://localhost:8080"
REACT_APP_WS_URL = "ws://localhost:8080"
FRONTEND_PORT = "80"

# Database Variables (will be overridden by Railway App variables)
DB_POSTGRES_DB = "consultra"
DB_POSTGRES_USER = "postgres"
DB_POSTGRES_PASSWORD = "maoirt"
DB_PORT = "5432" 