[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "prod"
DATABASE_URL = "jdbc:postgresql://db:5432/consultra"
DATABASE_USERNAME = "postgres"
DATABASE_PASSWORD = "maoirt"
NOTIFICATION_SERVICE_URL = "http://notification-service:8081"
CORS_ALLOWED_ORIGINS = "https://your-frontend-domain.railway.app,http://localhost:3000"
JWT_SECRET_KEY = "your-secret-key-here" 